# Site settings
title: Earn $$$
email: sherrala@topofmind.com
url: http://topofmind.com
description: "Come work with our A+++ Number One Team Awesome and earn much $$$ working FROM YOUR HOME."
skills: "Work From Anywhere - Receive Monies For Said Work - Sleep Sometimes"
meta_author: Herrala Sean
banner_title: Earn $$$ FROM HOME

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: TOMN Dev Team
  location: Sitting At
  social: Wasting Time
  credits: Blame

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/seanherrala
  - title: facebook
    url: http://facebook.com/sherrala

# Postal address (add as many lines as necessary)
address:
  - line: Spare Bedroom
  - line: St. Augustine FL 32084

# Credits content
credits: 'Sean Herrala is solely at fault for this. <a href="mailto:sherrala@topofmind.com">Hate Him</a>.'

# Build settings
markdown: kramdown
permalink: pretty
